# -*- coding: utf-8 -*-
"""Breast Cancer detection using Random Forest Classifier .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1M7uIPGKiPvVhHCIF6qg4jKzuDVdgYNwo

Import Libraries
"""

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

"""Data preprocessing"""

dataset=pd.read_csv('breast_cancer.csv')
X= dataset.iloc[:,1:-1].values
y=dataset.iloc[:,-1].values

"""**Splitting dataset into Training set and Test set**"""

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y, test_size=0.2,random_state=0)

from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 7, criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)

"""**Predicting Test set values**"""

y_pred=classifier.predict(X_test)

"""**Confusion matrix**"""

from sklearn.metrics import confusion_matrix,accuracy_score
conf=confusion_matrix(y_test,y_pred)
print(conf)
acc=accuracy_score(y_test,y_pred)
print(acc)

from sklearn.model_selection import cross_val_score
accuracies=cross_val_score(estimator=classifier,X=X_train,y=y_train,cv=10)
print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
print("Standard deviation: {:.2f} %".format(accuracies.std()*100))